name: Build Executables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            python-version: '3.11'
            architecture: arm64
            output-name: remove_watermark_macos
          - os: windows-latest
            python-version: '3.11'
            architecture: amd64
            output-name: remove_watermark_windows

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Verify Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --name ${{ matrix.output-name }} --add-data "SimHei.ttf:." watermark.py

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        pyinstaller --onefile --name ${{ matrix.output-name }} --add-data "SimHei.ttf;." watermark.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output-name }}
        path: dist/${{ matrix.output-name }}*